# Generated by Django 4.2.6 on 2023-10-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('NoAgence', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('tel', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('localisation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('boitePostale', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BordereauOp',
            fields=[
                ('date', models.DateTimeField()),
                ('idtransfer', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('msisdn', models.IntegerField(default=0)),
                ('number', models.IntegerField(null=True)),
                ('statement', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('debit', models.IntegerField(default=0)),
                ('fees', models.IntegerField(default=0)),
                ('previous', models.IntegerField()),
                ('post', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('noCaisse', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('compte', models.CharField(max_length=30)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.agence')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('refCNIB', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('noService', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Orion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomoper', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('reference', models.CharField(max_length=30)),
                ('idtransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.bordereauop')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.IntegerField()),
                ('refOp', models.CharField(default='', max_length=30)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.agence')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.agent')),
                ('caisse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controle.caisse')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.client')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.operateur')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.service')),
                ('typeOp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.typeoperation')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('tel', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.agence')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Consolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('reglement', models.BooleanField()),
                ('datereglement', models.DateTimeField()),
                ('bordereauOp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.bordereauop')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.nature')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.operation')),
            ],
        ),
        migrations.CreateModel(
            name='CompteOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compteop', models.CharField(max_length=30)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.operateur')),
            ],
        ),
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.agence')),
                ('compteOp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.compteop')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.direction')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='fonction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.fonction'),
        ),
    ]
