# Generated by Django 4.2.6 on 2023-10-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteop',
            name='agence',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='controle.agence'),
        ),
    ]
