# Generated by Django 4.1.5 on 2023-10-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_operation_bordereauop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='bordereauop',
        ),
    ]
