# Generated by Django 4.1.5 on 2023-10-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_remove_operation_bordereauop'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereauop',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controle.agence'),
        ),
        migrations.AddField(
            model_name='bordereauop',
            name='operateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controle.operateur'),
        ),
        migrations.AddField(
            model_name='consolidation',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controle.agence'),
        ),
        migrations.AddField(
            model_name='consolidation',
            name='operateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controle.operateur'),
        ),
    ]
